name: wallify
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_secure_storage: ^9.0.0
  flutter_wallpaper_manager: ^0.0.3
  fluttertoast: ^8.2.1
  get: ^4.6.6
  http: ^1.1.2
  lottie: ^2.6.0
  path_provider: ^2.0.2
  permission_handler: ^11.1.0
  share_plus: ^7.2.1
  shimmer: ^3.0.0
  url_launcher: ^6.2.2
  external_path: ^1.0.3

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
